[package]
name = "jp-ch2-regex-combinators"
version = "0.1.0"
authors = ["Justin <zallambo@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dev-dependencies]
# For comparison
regex = "*"
